import { useState } from "react";
import { ImageOff } from "lucide-react";

interface PlaceholderImageProps {
  /** Path under /public where the real asset should live, e.g. "/images/rooms/nile-view.jpg" */
  src: string;
  alt: string;
  /** Short label shown in the placeholder state, e.g. "Nile View Room" */
  label: string;
  className?: string;
  /** Set for above-the-fold images (e.g. the hero building) to skip lazy-loading. */
  eager?: boolean;
}

/**
 * Renders the real image if it exists at `src`; otherwise falls back to a
 * clearly-marked placeholder showing exactly which file to add and where.
 * No images are generated by this component — it only ever displays real
 * assets once they're dropped into /public at the given path.
 */
export default function PlaceholderImage({
  src,
  alt,
  label,
  className = "",
  eager = false,
}: PlaceholderImageProps) {
  const [hasError, setHasError] = useState(false);

  if (hasError) {
    return (
      <div
        className={`flex flex-col items-center justify-center gap-2 border border-dashed border-gold/50 bg-sand/20 text-center text-nile-deep ${className}`}
      >
        <ImageOff className="h-6 w-6 text-terracotta/70" aria-hidden="true" />
        <p className="px-4 text-sm font-medium">{label}</p>
        <code className="rounded bg-nile-deep/5 px-2 py-1 text-xs text-brown/70">{src}</code>
      </div>
    );
  }

  return (
    <img
      src={src}
      alt={alt}
      loading={eager ? "eager" : "lazy"}
      onError={() => setHasError(true)}
      className={`object-cover ${className}`}
    />
  );
}
